version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: make test-coverage

      - run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls

workflows:
  test:
    jobs:
      - test
