version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  test:
    executor:
      name: node/default

    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install
            - run: make test-coverage

      # More compact variant without hashsum check
      # - run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
      - run: |
          curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz
          curl -sLO https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-checksums.txt
          cat coveralls-checksums.txt | grep coveralls-linux.tar.gz | sha256sum --check
          tar -xzf coveralls-linux.tar.gz
          ./coveralls

workflows:
  test:
    jobs:
      - test
